### ISSUE TITLE
protractor 5.1.2 installs two versions of selenium-webdriver because of webdriver-js-extender

### ISSUE THREAD

**Issue by fr0** [angular/webdriver-js-extender#17]
- Node Version: `6.10.2`
- Protractor Version: `5.1.2`
- Angular Version: `4.3.3`
- Operating System and Version `Mac OS Sierra (10.12.6)`

Protractor has a dependency on `webdriver-js-extender@^1.0.0`, which has a dependency on `selenium-webdriver@^2.53.2`. However, Protractor itself installs `selenium-webdriver@3.0.1`.

The end result is that I get two copies of `selenium-webdriver` in my `node_modules` folder, at 3.5MB each. This seems excessive and unnecessary.

Consider this issue a request to move `webdriver-js-extender` to the latest version of `selenium-webdriver`, which would result in only one copy of it in my `node_modules` folder.

**Comment by NickTomlin** [comment]
I think this makes sense. 

I have a pull request for bumping this https://github.com/angular/webdriver-js-extender/pull/12 but i'll probably need some hand holding from @sjelin or @cnishina (feel free to re-route me!)

**Comment by light24bulbs** [comment]
This is still an issue.  Pulls in webdriver@2.53.3 which is wildly out of date.

**Comment by qiyigg** [comment]
fixed by #12
