### ISSUE TITLE
Update selenium-webdriver package version due to security issues

### ISSUE THREAD

**Issue by IgorSasovets** [angular/webdriver-js-extender#19]
Hi, Team!

First of all, thanks for all that you're doing! Recently I checked my package.json file of small project with [Snyk tool](https://snyk.io/). In generated report was issue related to selenium-webdriver package version (see screenshot below). They've already replaced [adm-zip with jszip](https://github.com/SeleniumHQ/selenium/commit/8e77b5402b30be159b5a8d435d5487647fbe544f) and it fixed this issue. For detailed description of vulnerability please take a look at [snyk article](https://snyk.io/vuln/npm:adm-zip:20180415). Please update version of selenium-webdriver. I can open a PR for it.
![screen shot 2018-06-04 at 12 31 29 pm](https://user-images.githubusercontent.com/27974884/40909821-3bf8ec80-67f3-11e8-8d5d-7c344d744b68.png)

**Comment by IgorSasovets** [comment]
@qiyigg , I think this issue can be closed now because you merged [appropriate PR](https://github.com/angular/webdriver-js-extender/pull/12)?

**Comment by qiyigg** [comment]
oh, yes, webdriver-js-extender already have a new release. I was working on update Protractor yesterday, Protractor should have a release today.

**Comment by IgorSasovets** [comment]
@qiyigg , thanks for all that you're doing for Protractor community!
