### ISSUE TITLE
Travis build is currently not running

### ISSUE THREAD

**Issue by NickTomlin** [angular/webdriver-js-extender#24]
@qiyigg I apparently don't have permissions for this repo so I can't enable the [travis build](https://travis-ci.org/angular/webdriver-js-extender) but it would be good to do that if we want to maintain this project. 

Let me know if I can help in any way. Thanks!

**Comment by kyliau** [comment]
We'll switch over to CircleCI. 
cc @josephperrott (I'm happy to do it, but I don't have admin access)
