### ISSUE TITLE
Generates too long path on Windows

### ISSUE THREAD

**Issue by Trojaner** [angular/webdriver-js-extender#27]
Visual Studio deployment fails because webdriver-js-extender generates paths which are too long on Windows (it fails to copy the output).

![](https://vgy.me/XGnzlW.png)

webdriver-js-extender@2.1.0
Node v8.9.1
Windows 10 x64 1803

Edit: #26 should fix it.

**Comment by AcidAndroid** [comment]
I have the same problem. I delete the node_modules and the problem remains. Does anyone solve it?

**Comment by briankoksal** [comment]
Same issue here. 

node_modules\webdriver-js-extender\built\built\built\built\built\built\built\built\built\built\built\built\built\built\built\built\spec\command_tests

**Comment by mkArtakMSFT** [comment]
This is indeed a source of pain. Hopefully this will be fixed soon, though given the age of this issue seems like not 👎

**Comment by SwintDC** [comment]
Does anyone have an idea what is causing this?

**Comment by kappa7194** [comment]
We're having problem with this in our project on Windows.

We're unable to delete the node_modules directories from either Command Prompt or Git Bash because the path length exceeds the one supported by Windows.

This prevents us from automating build/clean-ups.

Issue #29 is a duplicate of this one.

**Comment by tudorsibiu90** [comment]
I also experience this and I found no solution thus far. It's a deal breaker

**Comment by stoicad** [comment]
Same here, do you have a solution for this??

**Comment by kyliau** [comment]
This issue has been fixed in v2.2.0 release.
